const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //user
    CLIENT_LOGIN_SUCCESS: 'CLIENT_LOGIN_SUCCESS',
    CLIENT_PROCESS_LOGOUT: 'CLIENT_PROCESS_LOGOUT',
    GET_INFOR_CLIENT: 'GET_INFOR_CLIENT',

    //cart
    SET_INFOR_CART: 'SET_INFOR_CART',
    USER_NOT_LOGIN: 'USER_NOT_LOGIN'
})

export default actionTypes;